### ISSUE TITLE
Feature: Make colors of Postits configurable

### ISSUE THREAD

**Issue by moenka** [ocdtrekkie/scrumblr#12]
Hi, this is a feature request.

As the colors of the Postits can be used for special meanings (e.g. Task, Bug, Feature) I'd like to decide which color a new Postit has. This could be presented as a stack of postits with different colors from which I drag it to the wall.
Despite the scrum use the wall could be used for different organization scenarios this way.

**Comment by ocdtrekkie** [comment]
Hey @moenka! This repo is a fork of the upstream for Sandstorm.io support. (And I rarely have time to properly maintain it.) I probably wouldn't get such a feature unless it was implemented in https://github.com/aliasaria/scrumblr so I recommend requesting it there.

**Comment by moenka** [comment]
Oh sorry, I will put all feature requests to the upstream project.
