### ISSUE TITLE
Feature: Add avatar upload for users

### ISSUE THREAD

**Issue by moenka** [ocdtrekkie/scrumblr#13]
As a user,
I want to upload an avatar,
so I can be identified easier.

**Comment by ocdtrekkie** [comment]
As a Sandstorm.io support fork, I definitely wouldn't add this feature. If Scrumblr added avatar support, this fork would pull the avatar from a user's Sandstorm.io profile.

**Comment by moenka** [comment]
Sorry, I will close the issue and put it to the upstream.
